-- MySQL Script generated by MySQL Workbench
-- Wed May  8 15:07:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema map
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `map` ;

-- -----------------------------------------------------
-- Schema map
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `map` DEFAULT CHARACTER SET utf8 ;
USE `map` ;

-- -----------------------------------------------------
-- Table `map`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `map`.`usuario` ;

CREATE TABLE IF NOT EXISTS `map`.`usuario` (
  `idUsu` INT NOT NULL AUTO_INCREMENT,
  `nomeUsu` VARCHAR(150) NOT NULL,
  `cpfUsu` VARCHAR(16) NULL,
  `dtNascimentoUsu` DATE NOT NULL,
  `telefoneUsu` VARCHAR(20) NOT NULL,
  `emailUsu` VARCHAR(150) NOT NULL,
  `senhaUsu` VARCHAR(255) NOT NULL,
  `perfilUsu` VARCHAR(16) NOT NULL DEFAULT 'CLIENTE' COMMENT 'ADMINISTRADOR\nFUNCIONARIO\nCLIENTE',
  `situacaoUsu` VARCHAR(9) NOT NULL DEFAULT 'ATIVO' COMMENT 'ATIVO\nINATIVO\n',
  `enderecoUsu` VARCHAR(60) NULL,
  `numeroUsu` INT NULL,
  `complementoUsu` VARCHAR(50) NULL,
  `bairroUsu` VARCHAR(50) NULL,
  `cidadeUsu` VARCHAR(50) NULL,
  `ufUsu` VARCHAR(4) NULL,
  `cepUsu` VARCHAR(13) NULL,
  PRIMARY KEY (`idUsu`))
ENGINE = InnoDB;

INSERT INTO `usuario` (`idUsu`, `nomeUsu`, `cpfUsu`, `dtNascimentoUsu`, `telefoneUsu`, `emailUsu`, `senhaUsu`, `perfilUsu`, `situacaoUsu`, `enderecoUsu`, `numeroUsu`, `complementoUsu`, `bairroUsu`, `cidadeUsu`, `ufUsu`, `cepUsu`) VALUES
(1, 'Administrador', '264.185.950-50', '2000-05-08', '+55 (61) 98854-4752', 'admin@gmail.com', '$2y$10$MMtmbDOUy9Zl/7PvicXWP.H.sSwSxxdCEcROc7jCC0zdYwrOPS47u', 'Administrador', 'ATIVO', 'Quadra QN 11 Conjunto 3', 10, 'casa', 'Riacho Fundo II', 'Riacho Fundo II', 'DF', '71881-613'),
(2, 'João', '116.122.550-19', '1989-09-01', '+55 (61) 99966-5214', 'joao@gmail.com', '$2y$10$bc5vYuKs9d73eHtkRIXJc.v6dAOtbOsavbpBnBaqAgZ0FKQNkDhQK', 'Funcionario', 'ATIVO', 'Quadra QNL 8 Bloco B', 102, 'apartamento', 'Taguatinga Norte', 'Taguatinga', 'DF', '72155-812'),
(3, 'Regina Barbosa Merlonetti ', '310.818.628-07', '2000-11-11', '+55 (61) 95555-5555', 'regina@gmail.com', '$2y$10$0SCxQ3VKta03cavqEzhw/uwtX3CtlIY1Fmchg0i5PzYqwTo7OOBf.', 'CLIENTE', 'ATIVO', 'Rua Vitorino Carmilo', 10, NULL, 'Barra Funda', 'São Paulo', 'SP', '01153-000'),
(4, 'Ana Silva', '111.427.608-12', '1990-07-15', '+55 (61) 95555-5555', 'ana@gmail.com', '$2y$10$RwwHopZ8L/WqK1rsWhY2DOVNfBYeCxwWp8Zkll6x/v/r4nCUyU4zi', 'CLIENTE', 'ATIVO', 'Praça da Sé', 1000, NULL, 'Sé', 'São Paulo', 'SP', '01001-000'),
(5, 'Fernanda Almeida Barros', '156.810.758-77', '2000-11-22', '+55 (61) 95555-5555', 'fernanda@gmail.com', '$2y$10$JGBtWJq03tS5IDaEABsOuOOz488PuTSC6Fd9dlRcCrK8XVuiVu9cS', 'CLIENTE', 'ATIVO', 'Avenida das Nações Unidas', 40, NULL, 'Brooklin Paulista', 'São Paulo', 'SP', '04578-000'),
(6, 'Fernanda Almeida Barros', '111.427.608-12', '2000-12-26', '+55 (61) 99999-9999', 'fernanda@gmail.com', '$2y$10$.6mJ.5FE/QKbf9m1Y5Gl0u0zq/toWLYjitRZa0dsirDqa38caPxBu', 'CLIENTE', 'ATIVO', 'Travessa Deputado João Alberto', 10, NULL, 'Tibiri', 'São Luís', 'MA', '65095-110'),
(7, 'carlos beato', '321.754.178-24', '2000-12-23', '+55 (61) 95503-2325', 'carlos@gmail.com', '$2y$10$SmCo7/ZVbbRq7Lhx79a50.OeB2XFO5Cl.TFR32QWsMZNpAhH4LgZ2', 'CLIENTE', 'ATIVO', 'Avenida Onina Vieira dos Santos', 50, NULL, 'Muruci (Fazendinha)', 'Macapá', 'AP', '68911-356'),
(8, 'Maria do Rosario', '260.504.318-50', '2000-12-26', '+55 (55) 95666-6666', 'maria@gmail.com', '$2y$10$O2IMjrrR9eGECvjTWNETleZd5Etcxq.L6SNEr7ZyF.tLtJUkdPZca', 'CLIENTE', 'ATIVO', 'Rodovia BR-158', 40, NULL, 'Industrial', 'Pato Branco', 'PR', '85504-670'),
(9, 'karol Almeida', '335.545.078-22', '1988-11-14', '+55 (61) 95555-5555', 'karol@gmail.com', '$2y$10$CU0VF.f1u.W9UEFHmwHm5uWWmoGjSFYYmLdkpLwK68zDgoNTxycAq', 'CLIENTE', 'ATIVO', 'Rua Val Paraíso', 5122, NULL, 'Brejo da Guabiraba', 'Recife', 'PE', '52291-591'),
(10, 'Jose Almeida', '357.376.918-70', '1990-07-15', '+55 (61) 95859-8888', 'jose@gmail.com', '$2y$10$SAbcZ4VjILoagWN/etTjae09VvX7HDyIPCqLHVKZbAE8kcIYDgUCW', 'CLIENTE', 'ATIVO', 'Rua Antônio Guilhermino de Souza', 65, NULL, 'Cidades', 'Campina Grande', 'PB', '58421-805'),
(11, 'Reginaldo Rossi', '292.711.238-08', '1988-10-12', '+55 (61) 95875-2222', 'reginaldo@gmail.com', '$2y$10$uA4UVxqbonHqC3WQE5wHc.ySK9R6iBeouQkTH4n3ne533TUcvoUCS', 'CLIENTE', 'ATIVO', 'Rua Inácio José Negrão', 45, NULL, 'Jardim América', 'Chapecó', 'SC', '89803-530'),
(12, 'Julio cesar ', '357.376.918-70', '1988-04-15', '+55 (61) 98544-8999', 'julio@gmail.com', '$2y$10$iZHptSRCHajrUsmad7c6kOxqt2WBfdrMh7KWIl9yz40O8eE.74Nom', 'CLIENTE', 'ATIVO', 'Rua Jambú', 20, NULL, 'Jorge Teixeira', 'Manaus', 'AM', '69088-423'),
(13, 'Edisio Alercio', '291.303.858-14', '1998-10-12', '+55 (61) 98587-8877', 'edisio@gmail.com', '$2y$10$PSgd2zwC8.691tNKNyR.KuuQoWNVGFfJQzThjO3AUsYcYTqIBSsei', 'CLIENTE', 'ATIVO', 'Rua Constante Ramos', 45, NULL, 'Copacabana', 'Rio de Janeiro', 'RJ', '22051-011'),
(14, 'Ramon da Silva', '458.403.748-57', '1986-12-12', '+55 (61) 95535-9984', 'ramon@gmail.com', '$2y$10$wZrjpB89UgkdtQ/8FJYmmehZ3Bkf4JBPHwZ9nzlt5ZKXESe7A1cJy', 'CLIENTE', 'ATIVO', 'Rua de São Jorge', 12, NULL, 'Recife', 'Recife', 'PE', '50030-240'),
(15, 'Marcelia Da silva', '122.565.638-98', '1999-04-14', '+55 (61) 95998-8898', 'marcelia@gmail.com', '$2y$10$c5qEQ.52UcGXn7evDMG/tenAW6DDD/azxo50eFr94MJkc2mLpzutq', 'CLIENTE', 'ATIVO', 'Rua Antônio Moreira da Silva', 50, NULL, 'Lameiro', 'Crato', 'CE', '63112-140'),
(16, 'Catia Regina Rodrigues Santana ', '071.429.510-87', '1999-10-12', '+55 (61) 98566-6554', 'catia@gmail.com', '$2y$10$Op096EiH99G630RRyx3XC.4Ni4ExIDu5x9Pc4mM5B1mWK3lvKXqLi', 'CLIENTE', 'ATIVO', 'Rua Bartolomeu Lins Filho', 65, NULL, 'Clima Bom', 'Maceió', 'AL', '57071-290'),
(17, 'Claudia Arraia', '362.924.520-00', '1989-03-14', '+55 (61) 95884-5555', 'claudia@gmail.com', '$2y$10$4jzEpd8wzYXTkRC55rJ45uPQHiYIGlYKfGx4ADYyC.ygTRa8L0lMq', 'CLIENTE', 'ATIVO', 'Rua João Calmon', 21, NULL, 'Araçá', 'Linhares', 'ES', '29901-411'),
(18, 'Maria Clara', '662.348.220-29', '1988-10-12', '+55 (61) 98984-4744', 'maria@gmail.com', '$2y$10$OpaFSDdzw1uRQBQEpTbE0uUo5T6u3Lfzu3drQbvHVfEmafcXYuhPe', 'CLIENTE', 'ATIVO', 'Rua Carlos Chagas', 23, NULL, 'Caiçara', 'Campo Grande', 'MS', '79090-292'),
(19, 'Nazare Pontocom', '780.276.050-08', '1987-12-15', '+55 (61) 98844-5522', 'nazare@gmail.com', '$2y$10$KFjEqMBK0hbjdj9Sjop.uOmMRxxoRbJzzvhk6yXzvsPx6csZIbxuO', 'CLIENTE', 'ATIVO', 'Rua Formosa', 23, NULL, 'Jardim América', 'Sinop', 'MT', '78559-624'),
(20, 'Adriano Lopez', '908.218.590-30', '1981-10-12', '+55 (19) 96555-5588', 'adriano@gmail.com', '$2y$10$DbD/8t6Gw/Hef8x7xvodWeJH/FA.K3VlRVRpahGEhlKA56.ZSWP6e', 'CLIENTE', 'ATIVO', 'Rua Paulo Henrique Silva', 32, NULL, 'Bela Vista', 'Cachoeiro de Itapemirim', 'ES', '29316-016'),
(21, 'Sonia Alves', '257.815.900-99', '1985-10-12', '+55 (61) 95589-8447', 'sonia@gmail.com', '$2y$10$ZVk2OEYXN0hyJ/8ZNqHeD.h39EPbDXUt2V9fWy7hyoa8.YpAMO36y', 'CLIENTE', 'ATIVO', 'QNN 4 Conjunto M', 54, NULL, 'Ceilândia Sul (Ceilândia)', 'Brasília', 'DF', '72220-053');

-- -----------------------------------------------------
-- Table `map`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `map`.`pedido` ;

CREATE TABLE IF NOT EXISTS `map`.`pedido` (
  `idPed` INT NOT NULL AUTO_INCREMENT,
  `dataHoraPed` DATETIME NOT NULL,
  `valorTotalPed` DECIMAL(13,2) NOT NULL,
  `situacaoPed` VARCHAR(15) NOT NULL DEFAULT 'ABERTO' COMMENT 'FINALIZADO\nABERTO\nCANCELADO',
  `formaPagamentoUsu` VARCHAR(20) NOT NULL DEFAULT 'PENDENTE' COMMENT 'CREDITO\nDEBITO\nPIX\nBOLETO\nPENDENTE',
  `USUARIO_idUsu` INT NOT NULL,
  PRIMARY KEY (`idPed`),
  INDEX `fk_PEDIDO_USUARIO_idx` (`USUARIO_idUsu` ASC) ,
  CONSTRAINT `fk_PEDIDO_USUARIO`
    FOREIGN KEY (`USUARIO_idUsu`)
    REFERENCES `map`.`usuario` (`idUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `map`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `map`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `map`.`fornecedor` (
  `idFor` INT NOT NULL AUTO_INCREMENT,
  `nomeFor` VARCHAR(150) NOT NULL,
  `telefoneFor` VARCHAR(20) NOT NULL,
  `emailFor` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idFor`))
ENGINE = InnoDB;

INSERT INTO `fornecedor` (`idFor`, `nomeFor`, `telefoneFor`, `emailFor`) VALUES (NULL, 'Fiat', '+55 (61) 3566-1025', 'fiat@gmail.com');
INSERT INTO `fornecedor` (`idFor`, `nomeFor`, `telefoneFor`, `emailFor`) VALUES (NULL, 'Volkswagen', '+55 (61) 2301-4050', 'volks@gmail.com');
INSERT INTO `fornecedor` (`idFor`, `nomeFor`, `telefoneFor`, `emailFor`) VALUES (NULL, 'Pegeout', '+55 (61) 3965-1055', 'pegeout@gmail.com'), (NULL, 'Renault', '+55 (61) 3966-3666', 'renault@gmail.com');

-- -----------------------------------------------------
-- Table `map`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `map`.`produto` ;

CREATE TABLE IF NOT EXISTS `map`.`produto` (
  `idPro` INT NOT NULL AUTO_INCREMENT,
  `nomePro` VARCHAR(150) NOT NULL,
  `valorCompraPro` DECIMAL(13,2) NOT NULL,
  `valorVendaPro` DECIMAL(13,2) NOT NULL,
  `qtdEstoquePro` FLOAT NOT NULL,
  `imagemPro` VARCHAR(50) NULL,
  `codigoPro` VARCHAR(50) NOT NULL,
  `marcaPro` VARCHAR(50) NOT NULL DEFAULT 'NÃO INFORMADO' COMMENT 'NÃO INFORMADO\nRENAULT\nFIRESTONE\nMICHELLIN\nPIRELLI\nVOLKSWAGEN\nFIAT\nPEUGEOT',
  `categoriaPro` VARCHAR(50) NOT NULL COMMENT 'PNEU\nACESSORIOS\nPEÇAS\n',
  `descricaoPro` LONGTEXT NOT NULL,
  `FORNECEDOR_idFor` INT NOT NULL,
  PRIMARY KEY (`idPro`),
  INDEX `fk_PRODUTO_FORNECEDOR1_idx` (`FORNECEDOR_idFor` ASC) ,
  CONSTRAINT `fk_PRODUTO_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_idFor`)
    REFERENCES `map`.`fornecedor` (`idFor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



INSERT INTO `produto` (`idPro`, `nomePro`, `valorCompraPro`, `valorVendaPro`, `qtdEstoquePro`, `imagemPro`, `codigoPro`, `marcaPro`, `categoriaPro`, `descricaoPro`, `FORNECEDOR_idFor`) VALUES
(1, 'Óleo de Direção Hidráulica Semissintético', 150.00, 222.45, 10, 'imgProd/664136d2221e8.jpg', 'G-004-000-M2', 'Volkswagen', 'ACESSORIOS', '<p>Óleo de Direção Hidráulica original para seu VW, o código G-004-000-M2 aplica em Touareg Golf Polo New Beetle Passat Saveiro Fusca Jetta Bora Fox Santana SpaceFox Amarok Gol. Peças VW genuínas na sua loja virtual oficial da VW.<br></p>', 2),
(2, 'Interruptor de Pressão de Óleo de Motor ', 250.00, 339.58, 10, 'imgProd/6641376ee0f30.jpg', '036-919-081-D', 'Volkswagen', 'PEÇAS', '<p>Interruptor de Pressão de Óleo de Motor original para seu VW, o código 036-919-081-D aplica em Kombi Saveiro Nivus Amarok Voyage Polo Up! Golf Fox SpaceFox Jetta Tiguan Gol Parati Virtus T-Cross Taos. Peças VW genuínas na sua loja virtual oficial da VW.<br></p>', 2),
(3, 'Amortecedor de Suspensão Traseiro Direito (Passageiro) Esquerdo (Motorista', 350.00, 480.39, 10, 'imgProd/66413825b9bdc.jpg', 'JZZ-513-025', 'Volkswagen', 'PEÇAS', '<p>Amortecedor de Suspensão original para seu VW, o código JZZ-513-025 aplica em Fox Polo. Peças VW genuínas na sua loja virtual oficial da VW.<br></p>', 2),
(4, 'Pinça de Freio ', 900.00, 1.07, 10, 'imgProd/6641389107083.jpg', '6EA-615-424', 'Volkswagen', 'PEÇAS', '<p>Pinça de Freio original para seu VW, o código 6EA-615-424 aplica em Polo Virtus T-Cross Nivus. Peças VW genuínas na sua loja virtual oficial da VW.<br></p>', 2),
(5, 'Rede de Proteção Pe', 150.00, 259.97, 10, 'imgProd/6641390bf0af6.jpg', 'V04-010-029-M', 'Volkswagen', 'ACESSORIOS', '<p>Rede de Proteção Pet original para seu VW no código V04-010-029-M. Acessórios VW genuínos na sua loja virtual oficial da VW.<br></p>', 2),
(6, 'Capa de Parafuso de Roda', 7.00, 8.30, 10, 'imgProd/6641399a10847.jpg', ' 1K0-601-173- -9B9', 'Volkswagen', 'ACESSORIOS', '<p>Capa de Parafuso de Roda original para seu VW no código 1K0-601-173- -9B9. Acessórios VW genuínos na sua loja virtual oficial da VW.<br></p>', 2),
(7, 'Lixeira de Carro', 30.00, 41.04, 10, 'imgProd/664139f098c40.jpg', 'APR-057-005-AC', 'Volkswagen', 'ACESSORIOS', '<p>Lixeira de Carro original para seu VW no código APR-057-005-AC. Acessórios VW genuínos na sua loja virtual oficial da VW.<br></p>', 2),
(8, 'Kit de Câmera de Ré', 500.00, 554.06, 10, 'imgProd/66413a7019484.jpg', 'V04-011-006-A', 'Volkswagen', 'ACESSORIOS', '<p>Kit de Câmera de Ré original para seu VW no código V04-011-006-A. Acessórios VW genuínos na sua loja virtual oficial da VW.<br></p>', 2),
(9, 'Pneu 195/55 15 Polegadas', 650.00, 716.29, 10, 'imgProd/66413ad15d899.jpg', '5Z0-601-307-L -RPI ', 'Não informado', 'PNEU', '<p>Pneu original para seu VW, o código 5Z0-601-307-L -RPI aplica em . Peças VW genuínas na sua loja virtual oficial da VW.<br></p>', 1),
(10, 'Pneu 18 Polegadas', 650.00, 701.09, 10, 'imgProd/66413b1e238fb.jpg', '5QX-601-307- -RGY ', 'Volkswagen', 'PNEU', '<p>Pneu original para seu VW, o código 5QX-601-307- -RGY aplica em . Peças VW genuínas na sua loja virtual oficial da VW.<br></p>', 2),
(11, 'Pneu 185/60 15 Polegadas', 900.00, 969.88, 10, 'imgProd/66413b765ba55.jpg', 'V04-011-009-HA-RBS ', 'Volkswagen', 'PNEU', '<p>Pneu original para seu VW, o código V04-011-009-HA-RBS aplica em Up!. Peças VW genuínas na sua loja virtual oficial da VW.<br></p>', 2),
(12, 'Pneu 19 Polegadas', 800.00, 900.00, 10, 'imgProd/66413c01dba96.jpg', ' 5QX-601-307- -RGY ', 'Volkswagen', 'PNEU', '<p>Pneu original para seu VW, o código 5QX-601-307- -RGY aplica em . Peças VW genuínas na sua loja virtual oficial da VW.<br></p>', 2);


-- -----------------------------------------------------
-- Table `map`.`possui_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `map`.`possui_item` ;

CREATE TABLE IF NOT EXISTS `map`.`possui_item` (
  `PEDIDO_idPed` INT NOT NULL,
  `PRODUTO_idPro` INT NOT NULL,
  `qtdItemPro` FLOAT NOT NULL,
  `valorUnitarioPro` DECIMAL(13,2) NOT NULL,
  PRIMARY KEY (`PEDIDO_idPed`, `PRODUTO_idPro`),
  INDEX `fk_PEDIDO_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_idPro` ASC) ,
  INDEX `fk_PEDIDO_has_PRODUTO_PEDIDO1_idx` (`PEDIDO_idPed` ASC) ,
  CONSTRAINT `fk_PEDIDO_has_PRODUTO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPed`)
    REFERENCES `map`.`pedido` (`idPed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPro`)
    REFERENCES `map`.`produto` (`idPro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `map`.`avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `map`.`avaliacao` ;

CREATE TABLE IF NOT EXISTS `map`.`avaliacao` (
  `idAva` INT NOT NULL AUTO_INCREMENT,
  `dataAva` DATE NOT NULL,
  `textoAva` VARCHAR(200) NOT NULL,
  `qtdEstrelaAva` INT(5) NOT NULL COMMENT '1 a 5',
  `USUARIO_idUsu` INT NOT NULL,
  `PRODUTO_idPro` INT NOT NULL,
  PRIMARY KEY (`idAva`),
  INDEX `fk_AVALIACAO_USUARIO1_idx` (`USUARIO_idUsu` ASC) ,
  INDEX `fk_AVALIACAO_PRODUTO1_idx` (`PRODUTO_idPro` ASC) ,
  CONSTRAINT `fk_AVALIACAO_USUARIO1`
    FOREIGN KEY (`USUARIO_idUsu`)
    REFERENCES `map`.`usuario` (`idUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AVALIACAO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPro`)
    REFERENCES `map`.`produto` (`idPro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
