-- MySQL Script generated by MySQL Workbench
-- Wed May  8 15:07:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema map
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `map` ;

-- -----------------------------------------------------
-- Schema map
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `map` DEFAULT CHARACTER SET utf8 ;
USE `map` ;

-- -----------------------------------------------------
-- Table `map`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `map`.`usuario` ;

CREATE TABLE IF NOT EXISTS `map`.`usuario` (
  `idUsu` INT NOT NULL AUTO_INCREMENT,
  `nomeUsu` VARCHAR(150) NOT NULL,
  `cpfUsu` VARCHAR(16) NULL,
  `dtNascimentoUsu` DATE NOT NULL,
  `telefoneUsu` VARCHAR(20) NOT NULL,
  `emailUsu` VARCHAR(150) NOT NULL,
  `senhaUsu` VARCHAR(255) NOT NULL,
  `perfilUsu` VARCHAR(16) NOT NULL DEFAULT 'CLIENTE' COMMENT 'ADMINISTRADOR\nFUNCIONARIO\nCLIENTE',
  `situacaoUsu` VARCHAR(9) NOT NULL DEFAULT 'ATIVO' COMMENT 'ATIVO\nINATIVO\n',
  `enderecoUsu` VARCHAR(60) NULL,
  `numeroUsu` INT NULL,
  `complementoUsu` VARCHAR(50) NULL,
  `bairroUsu` VARCHAR(50) NULL,
  `cidadeUsu` VARCHAR(50) NULL,
  `ufUsu` VARCHAR(4) NULL,
  `cepUsu` VARCHAR(13) NULL,
  PRIMARY KEY (`idUsu`))
ENGINE = InnoDB;

INSERT INTO `usuario` (`idUsu`, `nomeUsu`, `cpfUsu`, `dtNascimentoUsu`, `telefoneUsu`, `emailUsu`, `senhaUsu`, `perfilUsu`, `situacaoUsu`, `enderecoUsu`, `numeroUsu`, `complementoUsu`, `bairroUsu`, `cidadeUsu`, `ufUsu`, `cepUsu`) VALUES (NULL, 'Administrador', '264.185.950-50', '2000-05-08', '+55 (61) 98854-4752', 'admin@gmail.com', '$2y$10$MMtmbDOUy9Zl/7PvicXWP.H.sSwSxxdCEcROc7jCC0zdYwrOPS47u', 'Administrador', 'ATIVO', 'Quadra QN 11 Conjunto 3', '10', 'casa', 'Riacho Fundo II', 'Riacho Fundo II', 'DF', '71881-613');

INSERT INTO `usuario` (`idUsu`, `nomeUsu`, `cpfUsu`, `dtNascimentoUsu`, `telefoneUsu`, `emailUsu`, `senhaUsu`, `perfilUsu`, `situacaoUsu`, `enderecoUsu`, `numeroUsu`, `complementoUsu`, `bairroUsu`, `cidadeUsu`, `ufUsu`, `cepUsu`) VALUES (NULL, 'João', '116.122.550-19', '1989-09-01', '+55 (61) 99966-5214', 'joao@gmail.com', '$2y$10$bc5vYuKs9d73eHtkRIXJc.v6dAOtbOsavbpBnBaqAgZ0FKQNkDhQK', 'Funcionario', 'ATIVO', 'Quadra QNL 8 Bloco B', '102', 'apartamento', 'Taguatinga Norte', 'Taguatinga', 'DF', '72155-812');

-- -----------------------------------------------------
-- Table `map`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `map`.`pedido` ;

CREATE TABLE IF NOT EXISTS `map`.`pedido` (
  `idPed` INT NOT NULL AUTO_INCREMENT,
  `dataHoraPed` DATETIME NOT NULL,
  `valorTotalPed` DECIMAL(13,2) NOT NULL,
  `situacaoPed` VARCHAR(15) NOT NULL DEFAULT 'ABERTO' COMMENT 'FINALIZADO\nABERTO\nCANCELADO',
  `formaPagamentoUsu` VARCHAR(20) NOT NULL DEFAULT 'PENDENTE' COMMENT 'CREDITO\nDEBITO\nPIX\nBOLETO\nPENDENTE',
  `USUARIO_idUsu` INT NOT NULL,
  PRIMARY KEY (`idPed`),
  INDEX `fk_PEDIDO_USUARIO_idx` (`USUARIO_idUsu` ASC) ,
  CONSTRAINT `fk_PEDIDO_USUARIO`
    FOREIGN KEY (`USUARIO_idUsu`)
    REFERENCES `map`.`usuario` (`idUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `map`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `map`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `map`.`fornecedor` (
  `idFor` INT NOT NULL AUTO_INCREMENT,
  `nomeFor` VARCHAR(150) NOT NULL,
  `telefoneFor` VARCHAR(20) NOT NULL,
  `emailFor` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idFor`))
ENGINE = InnoDB;

INSERT INTO `fornecedor` (`idFor`, `nomeFor`, `telefoneFor`, `emailFor`) VALUES (NULL, 'Fiat', '+55 (61) 3566-1025', 'fiat@gmail.com');
INSERT INTO `fornecedor` (`idFor`, `nomeFor`, `telefoneFor`, `emailFor`) VALUES (NULL, 'Volkswagen', '+55 (61) 2301-4050', 'volks@gmail.com');
INSERT INTO `fornecedor` (`idFor`, `nomeFor`, `telefoneFor`, `emailFor`) VALUES (NULL, 'Pegeout', '+55 (61) 3965-1055', 'pegeout@gmail.com'), (NULL, 'Renault', '+55 (61) 3966-3666', 'renault@gmail.com');

-- -----------------------------------------------------
-- Table `map`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `map`.`produto` ;

CREATE TABLE IF NOT EXISTS `map`.`produto` (
  `idPro` INT NOT NULL AUTO_INCREMENT,
  `nomePro` VARCHAR(150) NOT NULL,
  `valorCompraPro` DECIMAL(13,2) NOT NULL,
  `valorVendaPro` DECIMAL(13,2) NOT NULL,
  `qtdEstoquePro` FLOAT NOT NULL,
  `imagemPro` VARCHAR(50) NULL,
  `codigoPro` VARCHAR(50) NOT NULL,
  `marcaPro` VARCHAR(50) NOT NULL DEFAULT 'NÃO INFORMADO' COMMENT 'NÃO INFORMADO\nRENAULT\nFIRESTONE\nMICHELLIN\nPIRELLI\nVOLKSWAGEN\nFIAT\nPEUGEOT',
  `categoriaPro` VARCHAR(50) NOT NULL COMMENT 'PNEU\nACESSORIOS\nPEÇAS\n',
  `descricaoPro` LONGTEXT NOT NULL,
  `FORNECEDOR_idFor` INT NOT NULL,
  PRIMARY KEY (`idPro`),
  INDEX `fk_PRODUTO_FORNECEDOR1_idx` (`FORNECEDOR_idFor` ASC) ,
  CONSTRAINT `fk_PRODUTO_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_idFor`)
    REFERENCES `map`.`fornecedor` (`idFor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `map`.`possui_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `map`.`possui_item` ;

CREATE TABLE IF NOT EXISTS `map`.`possui_item` (
  `PEDIDO_idPed` INT NOT NULL,
  `PRODUTO_idPro` INT NOT NULL,
  `qtdItemPro` FLOAT NOT NULL,
  `valorUnitarioPro` DECIMAL(13,2) NOT NULL,
  PRIMARY KEY (`PEDIDO_idPed`, `PRODUTO_idPro`),
  INDEX `fk_PEDIDO_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_idPro` ASC) ,
  INDEX `fk_PEDIDO_has_PRODUTO_PEDIDO1_idx` (`PEDIDO_idPed` ASC) ,
  CONSTRAINT `fk_PEDIDO_has_PRODUTO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPed`)
    REFERENCES `map`.`pedido` (`idPed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPro`)
    REFERENCES `map`.`produto` (`idPro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `map`.`avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `map`.`avaliacao` ;

CREATE TABLE IF NOT EXISTS `map`.`avaliacao` (
  `idAva` INT NOT NULL AUTO_INCREMENT,
  `dataAva` DATE NOT NULL,
  `textoAva` VARCHAR(200) NOT NULL,
  `qtdEstrelaAva` INT(5) NOT NULL COMMENT '1 a 5',
  `USUARIO_idUsu` INT NOT NULL,
  `PRODUTO_idPro` INT NOT NULL,
  PRIMARY KEY (`idAva`),
  INDEX `fk_AVALIACAO_USUARIO1_idx` (`USUARIO_idUsu` ASC) ,
  INDEX `fk_AVALIACAO_PRODUTO1_idx` (`PRODUTO_idPro` ASC) ,
  CONSTRAINT `fk_AVALIACAO_USUARIO1`
    FOREIGN KEY (`USUARIO_idUsu`)
    REFERENCES `map`.`usuario` (`idUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AVALIACAO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_idPro`)
    REFERENCES `map`.`produto` (`idPro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
